version: '3'

networks:
  project-network:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - project-network

  kafka_broker1:
    image: bitnami/kafka:latest
    container_name: kafka_broker1
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - CREATE_KAFKA_TOPIC=test_topic1:3:1,test_topic2:3:1
    depends_on:
      - zookeeper
    networks:
      - project-network

